easy_admin:
    entities:
        # List the entity class name you want to manage
        Personnage:
            class: App\Entity\Personnage
            form:
                fields:
                    - nomPerso
                    - aptLeaderPerso
                    - aptPassPerso
                    - nomLiens
                    - { property: imageFile, type: vich_image }
                    - nomCategorie
            show:
                fields:
                    - { property: 'image', type: 'vich_image', base_path: '%app.path.image%' }

        Categorie:
            class: App\Entity\Categorie
        User:
            class: App\Entity\User
        Liens:
            class: App\Entity\Liens